### ISSUE TITLE
Pod Install warnings.

### ISSUE THREAD

**Issue by TheGuardian117** [xadrnd/display_sdk_ios_demo#1]
When you run a pod install, in the terminal log, I'm getting a lot of warnings. I'm wondering if it's possible for you to clean up these warnings

<img width="1409" alt="podinstall" src="https://user-images.githubusercontent.com/19479513/30232414-39f7a2ce-94ad-11e7-8f22-c22974bf2daa.png">

How to reproduce:
1. Download your test project.
2. Open up Terminal, can go to your repository.
3. Run a Pod Install.

Expected result: The pod install to complete with no warnings.
Actual result: All these warnings get printed.

If you have any questions, feel free to let me know.

**Comment by ghost** [comment]
We've added the license files. The issue should be resolved

**Comment by TheGuardian117** [comment]
Will test when the deployment target issue gets looked at.

**Comment by TheGuardian117** [comment]
Tested with version 1.1.1. The warnings are not there! Thank you very much for the fix!
