### ISSUE TITLE
XCode 9 support.

### ISSUE THREAD

**Issue by TheGuardian117** [xadrnd/display_sdk_ios_demo#3]
We're running into a compile time error while running your SDK on the Xcode 9 beta.
A screen shot running your Sample App with Xcode 9.0 beta.
<img width="271" alt="compile" src="https://user-images.githubusercontent.com/19479513/30299189-c7087eee-970b-11e7-8e66-61b86bc09aff.png">

Here is the error when we run your SDKs inside the GasBuddy app, on the Xcode 9.0 beta.
![error](https://user-images.githubusercontent.com/19479513/30299193-cf9f14aa-970b-11e7-8e17-95c2273f787d.png)

In order for us to use the new Xcode (which the GM version will be most likely available for developers tomorrow) we need your SDKs to be complied with Swift 3.2. The reason I'm requesting this now, is because Apple wants our iOS 11 supported version submitted, and ready to go live by the time iOS 11 is released to the public (which will most likely be next week). We do need this change done ASAP. 

Eventually we will like the SDK to be compiled with Swift 4, but that change is not mission critical at the moment.

**Comment by ghost** [comment]
We have compiled the SDK for Swift 3.2. Please use the following versions:

```
pod 'GroundTruthDisplaySDK', '~> 1.1.0'
pod 'GroundTruthCustomEventForGoogleMobileAd', '~> 1.1.0'
```

**Comment by TheGuardian117** [comment]
Thank you for the quick fix! 

When we updated out pod file, we got a warning, saying that your SDK ""requires a higher minimum deployment target". 

With this change did you drop support for iOS 9? If so, can you please still support iOS 9, we still need to support it.

**Comment by ghost** [comment]
We lowered the target to iOS 8. Please give it a try

**Comment by TheGuardian117** [comment]
Is the version still 1.1.0?

**Comment by ghost** [comment]
Yes, a `pod update` should bring in the newest spec, same version though.

**Comment by TheGuardian117** [comment]
Is there any way you can update the version as well. It would make it much easier on us, and the app distribution system that we use doesn't handle doing a pod update on a individual pod very well..

**Comment by ghost** [comment]
No problem, just use ```pod 'GroundTruthDisplaySDK', '~> 1.1.1'
pod 'GroundTruthCustomEventForGoogleMobileAd', '~> 1.1.1'```

**Comment by TheGuardian117** [comment]
Thank you very much for the quick turn around time! Everything is working correctly with the new version number!
